CREATE TABLE `IT202-M25-accountstats` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `actname` VARCHAR(255) UNIQUE NOT NULL,
  `kills` INT NOT NULL,
  `deaths` INT NOT NULL,
  `matches` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_api` TINYINT(1) DEFAULT '1'
);